[2024-12-30T07:03:04.378+0000] {processor.py:186} INFO - Started process (PID=127) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T07:03:04.381+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T07:03:04.416+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:03:04.409+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T07:03:04.701+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T07:03:06.444+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:03:06.443+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG:first_dag
[2024-12-30T07:03:06.453+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:03:06.453+0000] {override.py:1911} INFO - Created Permission View: can read on DAG:first_dag
[2024-12-30T07:03:06.458+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:03:06.458+0000] {override.py:1911} INFO - Created Permission View: can edit on DAG:first_dag
[2024-12-30T07:03:06.463+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:03:06.463+0000] {override.py:1911} INFO - Created Permission View: menu access on DAG Run:first_dag
[2024-12-30T07:03:06.467+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:03:06.467+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG Run:first_dag
[2024-12-30T07:03:06.472+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:03:06.472+0000] {override.py:1911} INFO - Created Permission View: can read on DAG Run:first_dag
[2024-12-30T07:03:06.477+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:03:06.476+0000] {override.py:1911} INFO - Created Permission View: can create on DAG Run:first_dag
[2024-12-30T07:03:06.477+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:03:06.477+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T07:03:06.486+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:03:06.486+0000] {dag.py:3262} INFO - Creating ORM DAG for first_dag
[2024-12-30T07:03:06.495+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:03:06.495+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to None, run_after=None
[2024-12-30T07:03:06.510+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 2.184 seconds
[2024-12-30T08:12:09.071+0000] {processor.py:186} INFO - Started process (PID=61) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:12:09.073+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:12:09.078+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:12:09.078+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:12:09.105+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:12:09.128+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:12:09.127+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:12:09.163+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:12:09.163+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to None, run_after=None
[2024-12-30T08:12:09.187+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.124 seconds
[2024-12-30T08:12:39.453+0000] {processor.py:186} INFO - Started process (PID=68) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:12:39.454+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:12:39.459+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:12:39.457+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:12:39.487+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:12:39.508+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:12:39.508+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:12:39.564+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:12:39.564+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to None, run_after=None
[2024-12-30T08:12:39.588+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.145 seconds
[2024-12-30T08:13:09.732+0000] {processor.py:186} INFO - Started process (PID=75) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:13:09.732+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:13:09.734+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:13:09.734+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:13:09.751+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:13:09.773+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:13:09.773+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:13:09.804+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:13:09.804+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to None, run_after=None
[2024-12-30T08:13:09.818+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.092 seconds
[2024-12-30T08:13:40.091+0000] {processor.py:186} INFO - Started process (PID=88) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:13:40.092+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:13:40.093+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:13:40.093+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:13:40.106+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:13:40.121+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:13:40.121+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:13:40.144+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:13:40.144+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to None, run_after=None
[2024-12-30T08:13:40.156+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.069 seconds
[2024-12-30T08:14:10.479+0000] {processor.py:186} INFO - Started process (PID=95) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:14:10.480+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:14:10.482+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:14:10.481+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:14:10.493+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:14:10.504+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:14:10.503+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:14:10.519+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:14:10.519+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to None, run_after=None
[2024-12-30T08:14:10.531+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.056 seconds
[2024-12-30T08:14:40.761+0000] {processor.py:186} INFO - Started process (PID=102) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:14:40.761+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:14:40.763+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:14:40.763+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:14:40.776+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:14:40.788+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:14:40.788+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:14:40.804+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:14:40.804+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to None, run_after=None
[2024-12-30T08:14:40.821+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.065 seconds
[2024-12-30T08:15:10.981+0000] {processor.py:186} INFO - Started process (PID=109) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:15:10.982+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:15:10.985+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:15:10.984+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:15:11.002+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:15:11.039+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:15:11.038+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:15:11.057+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:15:11.057+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to None, run_after=None
[2024-12-30T08:15:11.072+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.096 seconds
[2024-12-30T08:15:41.211+0000] {processor.py:186} INFO - Started process (PID=116) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:15:41.212+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:15:41.214+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:15:41.214+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:15:41.225+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:15:41.238+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:15:41.238+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:15:41.256+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:15:41.256+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to None, run_after=None
[2024-12-30T08:15:41.772+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.565 seconds
[2024-12-30T08:16:12.058+0000] {processor.py:186} INFO - Started process (PID=123) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:16:12.059+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:16:12.061+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:16:12.061+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:16:12.076+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:16:12.087+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:16:12.087+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:16:12.217+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:16:12.217+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to None, run_after=None
[2024-12-30T08:16:12.229+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.177 seconds
[2024-12-30T08:16:42.270+0000] {processor.py:186} INFO - Started process (PID=130) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:16:42.271+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:16:42.272+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:16:42.272+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:16:42.283+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:16:42.294+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:16:42.293+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:16:42.310+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:16:42.309+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to None, run_after=None
[2024-12-30T08:16:42.321+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.056 seconds
[2024-12-30T08:17:12.557+0000] {processor.py:186} INFO - Started process (PID=137) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:17:12.558+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:17:12.559+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:17:12.559+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:17:12.568+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:17:12.578+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:17:12.577+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:17:12.592+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:17:12.591+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to None, run_after=None
[2024-12-30T08:17:12.602+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.049 seconds
[2024-12-30T08:17:42.865+0000] {processor.py:186} INFO - Started process (PID=144) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:17:42.866+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:17:42.867+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:17:42.867+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:17:42.879+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:17:42.889+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:17:42.889+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:17:42.903+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:17:42.903+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to None, run_after=None
[2024-12-30T08:17:42.914+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.052 seconds
[2024-12-30T08:18:13.177+0000] {processor.py:186} INFO - Started process (PID=151) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:18:13.177+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:18:13.179+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:18:13.179+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:18:13.189+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:18:13.199+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:18:13.199+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:18:13.213+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:18:13.212+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to None, run_after=None
[2024-12-30T08:18:13.325+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.152 seconds
[2024-12-30T08:18:43.448+0000] {processor.py:186} INFO - Started process (PID=158) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:18:43.449+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:18:43.451+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:18:43.450+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:18:43.463+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:18:43.473+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:18:43.473+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:18:43.576+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:18:43.576+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to None, run_after=None
[2024-12-30T08:18:43.587+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.142 seconds
[2024-12-30T08:19:13.820+0000] {processor.py:186} INFO - Started process (PID=165) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:19:13.821+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:19:13.822+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:19:13.822+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:19:13.831+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:19:13.841+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:19:13.841+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:19:13.943+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:19:13.943+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to None, run_after=None
[2024-12-30T08:19:13.954+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.138 seconds
[2024-12-30T08:19:44.091+0000] {processor.py:186} INFO - Started process (PID=172) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:19:44.092+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:19:44.093+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:19:44.093+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:19:44.102+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:19:44.112+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:19:44.112+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:19:44.126+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:19:44.126+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to None, run_after=None
[2024-12-30T08:19:44.138+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.050 seconds
[2024-12-30T08:20:14.406+0000] {processor.py:186} INFO - Started process (PID=179) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:20:14.407+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:20:14.409+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:20:14.408+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:20:14.418+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:20:14.428+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:20:14.428+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:20:14.442+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:20:14.442+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to None, run_after=None
[2024-12-30T08:20:14.454+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.051 seconds
[2024-12-30T08:20:44.737+0000] {processor.py:186} INFO - Started process (PID=186) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:20:44.737+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:20:44.739+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:20:44.739+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:20:44.753+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:20:44.763+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:20:44.763+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:20:44.777+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:20:44.777+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to None, run_after=None
[2024-12-30T08:20:44.789+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.056 seconds
[2024-12-30T08:21:14.987+0000] {processor.py:186} INFO - Started process (PID=193) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:21:14.988+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:21:14.989+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:21:14.989+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:21:15.001+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:21:15.012+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:21:15.012+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:21:15.028+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:21:15.027+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to None, run_after=None
[2024-12-30T08:21:15.146+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.162 seconds
[2024-12-30T08:21:45.318+0000] {processor.py:186} INFO - Started process (PID=200) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:21:45.319+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:21:45.320+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:21:45.320+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:21:45.330+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:21:45.340+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:21:45.339+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:21:45.444+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:21:45.444+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to None, run_after=None
[2024-12-30T08:21:45.455+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.141 seconds
[2024-12-30T08:22:15.737+0000] {processor.py:186} INFO - Started process (PID=207) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:22:15.739+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:22:15.744+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:22:15.743+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:22:15.758+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:22:15.772+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:22:15.772+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:22:15.789+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:22:15.789+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to None, run_after=None
[2024-12-30T08:22:15.807+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.075 seconds
[2024-12-30T08:22:46.040+0000] {processor.py:186} INFO - Started process (PID=215) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:22:46.041+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:22:46.043+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:22:46.042+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:22:46.052+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:22:46.062+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:22:46.062+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:22:46.076+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:22:46.076+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to None, run_after=None
[2024-12-30T08:22:46.086+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.049 seconds
[2024-12-30T08:23:16.520+0000] {processor.py:186} INFO - Started process (PID=222) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:23:16.521+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:23:16.523+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:23:16.522+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:23:16.534+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:23:16.544+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:23:16.544+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:23:16.558+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:23:16.557+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to None, run_after=None
[2024-12-30T08:23:16.591+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.075 seconds
[2024-12-30T08:23:46.674+0000] {processor.py:186} INFO - Started process (PID=229) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:23:46.675+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:23:46.676+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:23:46.676+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:23:46.686+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:23:46.700+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:23:46.700+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:23:46.714+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:23:46.713+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to None, run_after=None
[2024-12-30T08:23:46.725+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.055 seconds
[2024-12-30T08:24:16.944+0000] {processor.py:186} INFO - Started process (PID=236) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:24:16.945+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:24:16.946+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:24:16.946+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:24:16.956+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:24:16.965+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:24:16.965+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:24:17.079+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:24:17.078+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to None, run_after=None
[2024-12-30T08:24:17.090+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.150 seconds
[2024-12-30T08:24:47.259+0000] {processor.py:186} INFO - Started process (PID=243) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:24:47.259+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:24:47.261+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:24:47.261+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:24:47.272+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:24:47.283+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:24:47.283+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:24:47.387+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:24:47.387+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to None, run_after=None
[2024-12-30T08:24:47.398+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.143 seconds
[2024-12-30T08:25:17.661+0000] {processor.py:186} INFO - Started process (PID=250) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:25:17.662+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:25:17.664+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:25:17.663+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:25:17.673+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:25:17.683+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:25:17.683+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:25:17.696+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:25:17.696+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to None, run_after=None
[2024-12-30T08:25:17.708+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.050 seconds
[2024-12-30T08:25:47.983+0000] {processor.py:186} INFO - Started process (PID=257) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:25:47.984+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:25:47.985+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:25:47.985+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:25:47.994+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:25:48.004+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:25:48.004+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:25:48.018+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:25:48.018+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to None, run_after=None
[2024-12-30T08:25:48.029+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.049 seconds
[2024-12-30T08:26:18.302+0000] {processor.py:186} INFO - Started process (PID=264) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:26:18.303+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:26:18.304+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:26:18.304+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:26:18.314+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:26:18.326+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:26:18.325+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:26:18.344+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:26:18.343+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to None, run_after=None
[2024-12-30T08:26:18.355+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.055 seconds
[2024-12-30T08:26:48.567+0000] {processor.py:186} INFO - Started process (PID=271) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:26:48.568+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:26:48.570+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:26:48.570+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:26:48.591+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:26:48.601+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:26:48.601+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:26:48.617+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:26:48.617+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to None, run_after=None
[2024-12-30T08:26:48.733+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.169 seconds
[2024-12-30T08:26:50.612+0000] {processor.py:186} INFO - Started process (PID=272) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:26:50.613+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:26:50.615+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:26:50.615+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:26:50.633+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:26:50.629+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 3, in <module>
    f
NameError: name 'f' is not defined
[2024-12-30T08:26:50.634+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:26:50.651+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.043 seconds
[2024-12-30T08:26:52.645+0000] {processor.py:186} INFO - Started process (PID=273) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:26:52.646+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:26:52.647+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:26:52.647+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:26:52.655+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:26:52.654+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2024-12-30T08:26:52.655+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:26:52.667+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.026 seconds
[2024-12-30T08:26:53.674+0000] {processor.py:186} INFO - Started process (PID=274) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:26:53.675+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:26:53.677+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:26:53.676+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:26:53.690+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:26:53.688+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 3
    from 
         ^
SyntaxError: invalid syntax
[2024-12-30T08:26:53.691+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:26:53.708+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.040 seconds
[2024-12-30T08:26:55.741+0000] {processor.py:186} INFO - Started process (PID=275) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:26:55.742+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:26:55.744+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:26:55.743+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:26:55.756+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:26:55.755+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 3
    from dat
            ^
SyntaxError: invalid syntax
[2024-12-30T08:26:55.756+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:26:55.770+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.032 seconds
[2024-12-30T08:26:59.792+0000] {processor.py:186} INFO - Started process (PID=276) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:26:59.792+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:26:59.795+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:26:59.794+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:26:59.802+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:26:59.801+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 3
    from datetime 
                  ^
SyntaxError: invalid syntax
[2024-12-30T08:26:59.802+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:26:59.813+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.025 seconds
[2024-12-30T08:27:01.832+0000] {processor.py:186} INFO - Started process (PID=277) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:01.833+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:27:01.839+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:27:01.839+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:01.848+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:27:01.847+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 3
    from datetime import
                        ^
SyntaxError: invalid syntax
[2024-12-30T08:27:01.848+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:01.903+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.075 seconds
[2024-12-30T08:27:02.943+0000] {processor.py:186} INFO - Started process (PID=278) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:02.948+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:27:02.980+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:27:02.979+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:02.997+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:27:02.996+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 3
    from datetime import 
                         ^
SyntaxError: invalid syntax
[2024-12-30T08:27:02.998+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:03.963+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 1.083 seconds
[2024-12-30T08:27:04.931+0000] {processor.py:186} INFO - Started process (PID=279) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:04.940+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:27:04.971+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:27:04.969+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:05.009+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:27:04.997+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 3, in <module>
    from datetime import data
ImportError: cannot import name 'data' from 'datetime' (/usr/local/lib/python3.12/datetime.py). Did you mean: 'date'?
[2024-12-30T08:27:05.010+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:05.023+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.118 seconds
[2024-12-30T08:27:10.045+0000] {processor.py:186} INFO - Started process (PID=280) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:10.045+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:27:10.047+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:27:10.047+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:10.064+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:10.074+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:27:10.074+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:27:10.201+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:27:10.201+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to None, run_after=None
[2024-12-30T08:27:10.215+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.174 seconds
[2024-12-30T08:27:15.114+0000] {processor.py:186} INFO - Started process (PID=287) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:15.115+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:27:15.116+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:27:15.116+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:15.133+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:15.147+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:27:15.147+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:27:15.266+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:27:15.266+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to None, run_after=None
[2024-12-30T08:27:15.277+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.167 seconds
[2024-12-30T08:27:21.342+0000] {processor.py:186} INFO - Started process (PID=288) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:21.342+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:27:21.344+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:27:21.344+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:21.353+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:27:21.353+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 11
    ) as dag :
    ^
SyntaxError: positional argument follows keyword argument
[2024-12-30T08:27:21.354+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:21.365+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.026 seconds
[2024-12-30T08:27:22.377+0000] {processor.py:186} INFO - Started process (PID=289) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:22.378+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:27:22.379+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:27:22.379+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:22.386+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:27:22.386+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 11
    ) as dag :
    ^
SyntaxError: positional argument follows keyword argument
[2024-12-30T08:27:22.387+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:22.398+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.025 seconds
[2024-12-30T08:27:26.454+0000] {processor.py:186} INFO - Started process (PID=290) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:26.454+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:27:26.457+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:27:26.456+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:26.480+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:27:26.479+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 11
    ) as dag :
    ^
SyntaxError: positional argument follows keyword argument
[2024-12-30T08:27:26.481+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:26.498+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.048 seconds
[2024-12-30T08:27:27.546+0000] {processor.py:186} INFO - Started process (PID=291) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:27.547+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:27:27.549+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:27:27.548+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:27.556+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:27:27.556+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 10
    start_date=
    ^^^^^^^^^^^
SyntaxError: expected argument value expression
[2024-12-30T08:27:27.557+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:27.568+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.025 seconds
[2024-12-30T08:27:31.596+0000] {processor.py:186} INFO - Started process (PID=292) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:31.596+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:27:31.598+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:27:31.598+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:31.614+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:27:31.608+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 7, in <module>
    with DAG (
         ^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 619, in __init__
    tz = pendulum.instance(start_date, tz=tzinfo).timezone
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pendulum/__init__.py", line 244, in instance
    return DateTime.instance(obj, tz=tz)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pendulum/datetime.py", line 133, in instance
    tz = pendulum._safe_timezone(tz, dt=dt)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pendulum/__init__.py", line 124, in _safe_timezone
    return timezone(obj)
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pendulum/__init__.py", line 83, in timezone
    if name.lower() == "utc":
       ^^^^^^^^^^
AttributeError: 'getset_descriptor' object has no attribute 'lower'
[2024-12-30T08:27:31.615+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:31.626+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.035 seconds
[2024-12-30T08:27:32.632+0000] {processor.py:186} INFO - Started process (PID=293) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:32.632+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:27:32.634+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:27:32.634+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:32.657+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:27:32.655+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 10, in <module>
    start_date=datetime()
               ^^^^^^^^^^
TypeError: function missing required argument 'year' (pos 1)
[2024-12-30T08:27:32.658+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:32.669+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.041 seconds
[2024-12-30T08:27:35.691+0000] {processor.py:186} INFO - Started process (PID=294) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:35.692+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:27:35.693+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:27:35.693+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:35.705+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:27:35.704+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 10, in <module>
    start_date=datetime(2024)
               ^^^^^^^^^^^^^^
TypeError: function missing required argument 'month' (pos 2)
[2024-12-30T08:27:35.706+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:35.717+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.030 seconds
[2024-12-30T08:27:37.720+0000] {processor.py:186} INFO - Started process (PID=295) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:37.721+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:27:37.722+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:27:37.722+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:37.736+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:27:37.734+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 10, in <module>
    start_date=datetime(2024,)
               ^^^^^^^^^^^^^^^
TypeError: function missing required argument 'month' (pos 2)
[2024-12-30T08:27:37.737+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:37.748+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.031 seconds
[2024-12-30T08:27:39.785+0000] {processor.py:186} INFO - Started process (PID=296) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:39.786+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:27:39.789+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:27:39.789+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:39.812+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:27:39.801+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 10, in <module>
    start_date=datetime(2024, )
               ^^^^^^^^^^^^^^^^
TypeError: function missing required argument 'month' (pos 2)
[2024-12-30T08:27:39.813+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:27:39.827+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.047 seconds
[2024-12-30T08:28:02.985+0000] {processor.py:186} INFO - Started process (PID=303) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:02.986+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:28:02.987+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:28:02.987+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:03.005+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:28:02.997+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 10, in <module>
    start_date=datetime(2024, 3)
               ^^^^^^^^^^^^^^^^^
TypeError: function missing required argument 'day' (pos 3)
[2024-12-30T08:28:03.007+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:03.021+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.041 seconds
[2024-12-30T08:28:06.049+0000] {processor.py:186} INFO - Started process (PID=304) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:06.050+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:28:06.053+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:28:06.052+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:06.075+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:28:06.072+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 10, in <module>
    start_date=datetime(2024, 7)
               ^^^^^^^^^^^^^^^^^
TypeError: function missing required argument 'day' (pos 3)
[2024-12-30T08:28:06.076+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:06.095+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.052 seconds
[2024-12-30T08:28:09.088+0000] {processor.py:186} INFO - Started process (PID=305) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:09.089+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:28:09.091+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:28:09.090+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:09.103+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:28:09.100+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 10, in <module>
    start_date=datetime(2024, 12, )
               ^^^^^^^^^^^^^^^^^^^^
TypeError: function missing required argument 'day' (pos 3)
[2024-12-30T08:28:09.105+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:09.117+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.033 seconds
[2024-12-30T08:28:11.153+0000] {processor.py:186} INFO - Started process (PID=312) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:11.154+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:28:11.156+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:28:11.156+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:11.171+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:11.448+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:28:11.448+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:28:11.461+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:28:11.461+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to 2024-12-30 00:00:00+00:00, run_after=2024-12-31 00:00:00+00:00
[2024-12-30T08:28:11.474+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.324 seconds
[2024-12-30T08:28:14.188+0000] {processor.py:186} INFO - Started process (PID=313) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:14.190+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:28:14.192+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:28:14.192+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:14.205+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:14.213+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:28:14.213+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:28:14.229+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:28:14.229+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to 2024-12-30 00:00:00+00:00, run_after=2024-12-31 00:00:00+00:00
[2024-12-30T08:28:14.243+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.059 seconds
[2024-12-30T08:28:18.235+0000] {processor.py:186} INFO - Started process (PID=314) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:18.236+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:28:18.238+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:28:18.238+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:18.252+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:18.260+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:28:18.260+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-30T08:28:18.275+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:28:18.275+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to 2024-12-30 15:00:00+00:00, run_after=2024-12-31 15:00:00+00:00
[2024-12-30T08:28:18.289+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.057 seconds
[2024-12-30T08:28:29.385+0000] {processor.py:186} INFO - Started process (PID=315) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:29.386+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:28:29.388+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:28:29.387+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:29.394+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:28:29.394+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12
    ) as dag :
    ^
SyntaxError: positional argument follows keyword argument
[2024-12-30T08:28:29.395+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:29.406+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.024 seconds
[2024-12-30T08:28:37.480+0000] {processor.py:186} INFO - Started process (PID=316) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:37.481+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:28:37.483+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:28:37.482+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:37.489+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:28:37.489+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12
    ) as dag :
    ^
SyntaxError: positional argument follows keyword argument
[2024-12-30T08:28:37.490+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:37.501+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.024 seconds
[2024-12-30T08:28:39.518+0000] {processor.py:186} INFO - Started process (PID=317) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:39.518+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:28:39.520+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:28:39.520+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:39.527+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:28:39.526+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12
    ) as dag :
    ^
SyntaxError: positional argument follows keyword argument
[2024-12-30T08:28:39.527+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:39.537+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.023 seconds
[2024-12-30T08:28:42.571+0000] {processor.py:186} INFO - Started process (PID=324) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:42.572+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:28:42.573+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:28:42.573+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:42.586+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:28:42.585+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 7, in <module>
    with DAG (
         ^^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-12-30T08:28:42.587+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:42.599+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.032 seconds
[2024-12-30T08:28:43.592+0000] {processor.py:186} INFO - Started process (PID=325) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:43.592+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:28:43.594+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:28:43.594+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:43.603+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:28:43.602+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 7, in <module>
    with DAG (
         ^^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-12-30T08:28:43.604+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:43.616+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.028 seconds
[2024-12-30T08:28:46.662+0000] {processor.py:186} INFO - Started process (PID=326) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:46.663+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:28:46.664+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:28:46.664+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:46.676+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:28:46.674+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 7, in <module>
    with DAG (
         ^^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-12-30T08:28:46.677+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:46.689+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.030 seconds
[2024-12-30T08:28:53.739+0000] {processor.py:186} INFO - Started process (PID=327) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:53.740+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:28:53.741+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:28:53.741+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:53.762+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:28:53.761+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    with DAG (
         ^^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-12-30T08:28:53.763+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:53.775+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.040 seconds
[2024-12-30T08:28:55.767+0000] {processor.py:186} INFO - Started process (PID=328) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:55.767+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:28:55.769+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:28:55.769+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:55.776+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:28:55.776+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 6
    def
       ^
SyntaxError: invalid syntax
[2024-12-30T08:28:55.777+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:55.790+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.027 seconds
[2024-12-30T08:28:56.849+0000] {processor.py:186} INFO - Started process (PID=329) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:56.850+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:28:56.851+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:28:56.851+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:56.863+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:28:56.861+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 6, in <module>
    defaul
NameError: name 'defaul' is not defined
[2024-12-30T08:28:56.864+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:28:56.877+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.031 seconds
[2024-12-30T08:29:00.913+0000] {processor.py:186} INFO - Started process (PID=330) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:00.914+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:29:00.916+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:29:00.916+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:00.928+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:29:00.924+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 6, in <module>
    default_args
NameError: name 'default_args' is not defined
[2024-12-30T08:29:00.931+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:00.942+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.032 seconds
[2024-12-30T08:29:02.962+0000] {processor.py:186} INFO - Started process (PID=331) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:02.963+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:29:02.965+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:29:02.964+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:02.993+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:29:02.975+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    with DAG (
         ^^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-12-30T08:29:02.994+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:03.006+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.047 seconds
[2024-12-30T08:29:05.002+0000] {processor.py:186} INFO - Started process (PID=332) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:05.004+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:29:05.006+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:29:05.005+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:05.028+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:29:05.022+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 11, in <module>
    with DAG (
         ^^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-12-30T08:29:05.029+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:05.040+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.043 seconds
[2024-12-30T08:29:10.122+0000] {processor.py:186} INFO - Started process (PID=333) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:10.123+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:29:10.125+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:29:10.124+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:10.149+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:29:10.146+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 11, in <module>
    with DAG (
         ^^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-12-30T08:29:10.150+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:10.162+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.045 seconds
[2024-12-30T08:29:14.181+0000] {processor.py:186} INFO - Started process (PID=340) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:14.182+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:29:14.184+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:29:14.183+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:14.207+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:29:14.205+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 11, in <module>
    with DAG (
         ^^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-12-30T08:29:14.208+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:14.219+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.042 seconds
[2024-12-30T08:29:16.241+0000] {processor.py:186} INFO - Started process (PID=341) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:16.241+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:29:16.243+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:29:16.243+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:16.258+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:29:16.256+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 11, in <module>
    with DAG (
         ^^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-12-30T08:29:16.259+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:16.271+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.034 seconds
[2024-12-30T08:29:18.308+0000] {processor.py:186} INFO - Started process (PID=342) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:18.309+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:29:18.310+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:29:18.310+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:18.322+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:29:18.320+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    with DAG (
         ^^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-12-30T08:29:18.323+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:18.335+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.030 seconds
[2024-12-30T08:29:21.379+0000] {processor.py:186} INFO - Started process (PID=343) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:21.380+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:29:21.381+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:29:21.381+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:21.388+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:29:21.387+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 8
    retries
          ^
SyntaxError: ':' expected after dictionary key
[2024-12-30T08:29:21.388+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:21.400+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.025 seconds
[2024-12-30T08:29:24.427+0000] {processor.py:186} INFO - Started process (PID=344) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:24.428+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:29:24.429+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:29:24.429+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:24.435+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:29:24.435+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 8
    retries'
           ^
SyntaxError: unterminated string literal (detected at line 8)
[2024-12-30T08:29:24.436+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:24.449+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.026 seconds
[2024-12-30T08:29:26.487+0000] {processor.py:186} INFO - Started process (PID=345) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:26.488+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:29:26.489+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:29:26.488+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:26.497+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:29:26.497+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 8
    'retries'
            ^
SyntaxError: ':' expected after dictionary key
[2024-12-30T08:29:26.498+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:26.509+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.025 seconds
[2024-12-30T08:29:30.546+0000] {processor.py:186} INFO - Started process (PID=346) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:30.547+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:29:30.548+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:29:30.547+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:30.556+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:29:30.555+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 8
    'retries': 
             ^
SyntaxError: expression expected after dictionary key and ':'
[2024-12-30T08:29:30.556+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:30.567+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.024 seconds
[2024-12-30T08:29:31.597+0000] {processor.py:186} INFO - Started process (PID=347) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:31.597+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:29:31.598+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:29:31.598+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:31.623+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:29:31.613+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 12, in <module>
    with DAG (
         ^^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-12-30T08:29:31.624+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:31.635+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.042 seconds
[2024-12-30T08:29:32.623+0000] {processor.py:186} INFO - Started process (PID=348) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:32.624+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:29:32.625+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:29:32.625+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:32.636+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:29:32.634+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 13, in <module>
    with DAG (
         ^^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-12-30T08:29:32.636+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:32.647+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.028 seconds
[2024-12-30T08:29:34.722+0000] {processor.py:186} INFO - Started process (PID=349) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:34.724+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:29:34.725+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:29:34.725+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:34.739+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:29:34.738+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9
    re
     ^
SyntaxError: ':' expected after dictionary key
[2024-12-30T08:29:34.740+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:34.751+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.033 seconds
[2024-12-30T08:29:43.811+0000] {processor.py:186} INFO - Started process (PID=356) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:43.811+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:29:43.812+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:29:43.812+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:43.822+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:29:43.822+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9
    're'
       ^
SyntaxError: ':' expected after dictionary key
[2024-12-30T08:29:43.823+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:43.834+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.027 seconds
[2024-12-30T08:29:48.888+0000] {processor.py:186} INFO - Started process (PID=357) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:48.889+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:29:48.890+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:29:48.890+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:48.897+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:29:48.897+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9
    'retry_delay'
                ^
SyntaxError: ':' expected after dictionary key
[2024-12-30T08:29:48.898+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:48.909+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.024 seconds
[2024-12-30T08:29:54.954+0000] {processor.py:186} INFO - Started process (PID=358) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:54.955+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:29:54.956+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:29:54.956+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:54.963+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:29:54.962+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9
    'retry_delay':
                 ^
SyntaxError: expression expected after dictionary key and ':'
[2024-12-30T08:29:54.963+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:29:54.973+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.023 seconds
[2024-12-30T08:30:00.037+0000] {processor.py:186} INFO - Started process (PID=359) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:00.037+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:30:00.038+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:30:00.038+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:00.046+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:30:00.045+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 3
    from datetime import datetime, 
                                   ^
SyntaxError: trailing comma not allowed without surrounding parentheses
[2024-12-30T08:30:00.046+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:00.058+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.025 seconds
[2024-12-30T08:30:06.130+0000] {processor.py:186} INFO - Started process (PID=360) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:06.132+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:30:06.133+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:30:06.132+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:06.145+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:30:06.144+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9
    'retry_delay':
                 ^
SyntaxError: expression expected after dictionary key and ':'
[2024-12-30T08:30:06.146+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:06.163+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.039 seconds
[2024-12-30T08:30:07.183+0000] {processor.py:186} INFO - Started process (PID=361) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:07.184+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:30:07.185+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:30:07.184+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:07.192+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:30:07.192+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9
    'retry_delay':
                 ^
SyntaxError: expression expected after dictionary key and ':'
[2024-12-30T08:30:07.193+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:07.203+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.024 seconds
[2024-12-30T08:30:11.240+0000] {processor.py:186} INFO - Started process (PID=368) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:11.241+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:30:11.242+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:30:11.241+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:11.254+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:30:11.252+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    'retry_delay': time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-12-30T08:30:11.255+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:11.266+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.029 seconds
[2024-12-30T08:30:12.274+0000] {processor.py:186} INFO - Started process (PID=369) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:12.274+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:30:12.275+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:30:12.275+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:12.288+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:30:12.286+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 13, in <module>
    with DAG (
         ^^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-12-30T08:30:12.289+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:12.300+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.030 seconds
[2024-12-30T08:30:17.347+0000] {processor.py:186} INFO - Started process (PID=370) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:17.348+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:30:17.349+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:30:17.349+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:17.367+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:30:17.365+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 13, in <module>
    with DAG (
         ^^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-12-30T08:30:17.367+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:17.380+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.037 seconds
[2024-12-30T08:30:20.404+0000] {processor.py:186} INFO - Started process (PID=371) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:20.405+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:30:20.406+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:30:20.406+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:20.417+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:30:20.416+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    'retry_delay': timedelta(min)
                   ^^^^^^^^^^^^^^
TypeError: unsupported type for timedelta days component: builtin_function_or_method
[2024-12-30T08:30:20.418+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:20.429+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.029 seconds
[2024-12-30T08:30:23.459+0000] {processor.py:186} INFO - Started process (PID=372) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:23.460+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:30:23.461+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:30:23.461+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:23.469+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:30:23.468+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9
    'retry_delay': timedelta(minutes=)
                             ^^^^^^^^
SyntaxError: expected argument value expression
[2024-12-30T08:30:23.469+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:23.480+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.025 seconds
[2024-12-30T08:30:24.500+0000] {processor.py:186} INFO - Started process (PID=373) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:24.501+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:30:24.502+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:30:24.502+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:24.518+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:30:24.516+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 13, in <module>
    with DAG (
         ^^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-12-30T08:30:24.524+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:24.536+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.040 seconds
[2024-12-30T08:30:26.525+0000] {processor.py:186} INFO - Started process (PID=374) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:26.526+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:30:26.526+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:30:26.526+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:26.550+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:30:26.547+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 13, in <module>
    with DAG (
         ^^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-12-30T08:30:26.550+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:26.562+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.041 seconds
[2024-12-30T08:30:28.591+0000] {processor.py:186} INFO - Started process (PID=375) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:28.592+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:30:28.593+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:30:28.593+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:28.609+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:30:28.606+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 13, in <module>
    with DAG (
         ^^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-12-30T08:30:28.610+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:28.623+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.036 seconds
[2024-12-30T08:30:40.707+0000] {processor.py:186} INFO - Started process (PID=376) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:40.708+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:30:40.709+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:30:40.709+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:40.724+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:30:40.723+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 15
    def
    ^^^
SyntaxError: invalid syntax
[2024-12-30T08:30:40.724+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:40.739+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.035 seconds
[2024-12-30T08:30:42.749+0000] {processor.py:186} INFO - Started process (PID=383) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:42.750+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:30:42.751+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:30:42.751+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:42.758+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:30:42.757+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 15
    default_args
    ^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-12-30T08:30:42.758+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:42.770+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.024 seconds
[2024-12-30T08:30:43.794+0000] {processor.py:186} INFO - Started process (PID=384) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:43.794+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:30:43.795+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:30:43.795+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:43.808+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:30:43.808+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 16
    description="This is first dag",
               ^
SyntaxError: invalid syntax
[2024-12-30T08:30:43.809+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:43.820+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.031 seconds
[2024-12-30T08:30:45.836+0000] {processor.py:186} INFO - Started process (PID=385) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:45.838+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:30:45.842+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:30:45.841+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:45.862+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:30:45.860+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 15
    default_args = default_args
                   
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-12-30T08:30:45.863+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:45.882+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.053 seconds
[2024-12-30T08:30:46.880+0000] {processor.py:186} INFO - Started process (PID=386) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:46.880+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:30:46.881+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:30:46.881+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:46.906+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:30:46.903+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 13, in <module>
    with DAG (
         ^^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-12-30T08:30:46.906+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:30:46.919+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.043 seconds
[2024-12-30T08:31:03.045+0000] {processor.py:186} INFO - Started process (PID=387) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:31:03.046+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:31:03.047+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:31:03.047+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:31:03.054+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:31:03.054+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 4
    from
        ^
SyntaxError: invalid syntax
[2024-12-30T08:31:03.055+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:31:03.067+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.025 seconds
[2024-12-30T08:31:06.084+0000] {processor.py:186} INFO - Started process (PID=388) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:31:06.085+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:31:06.085+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:31:06.085+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:31:06.103+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:31:06.101+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 13, in <module>
    with DAG (
         ^^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-12-30T08:31:06.105+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:31:06.122+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.043 seconds
[2024-12-30T08:31:08.138+0000] {processor.py:186} INFO - Started process (PID=389) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:31:08.139+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:31:08.140+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:31:08.140+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:31:08.161+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:31:08.159+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 14, in <module>
    with DAG (
         ^^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-12-30T08:31:08.162+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:31:08.177+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.044 seconds
[2024-12-30T08:31:09.215+0000] {processor.py:186} INFO - Started process (PID=390) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:31:09.216+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:31:09.217+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:31:09.216+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:31:09.237+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:31:09.227+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 2, in <module>
    frop
NameError: name 'frop' is not defined
[2024-12-30T08:31:09.238+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:31:09.250+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.039 seconds
[2024-12-30T08:31:12.255+0000] {processor.py:186} INFO - Started process (PID=397) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:31:12.255+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:31:12.256+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:31:12.256+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:31:12.264+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:31:12.263+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 2
    from air
            ^
SyntaxError: invalid syntax
[2024-12-30T08:31:12.264+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:31:12.276+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.025 seconds
[2024-12-30T08:31:15.320+0000] {processor.py:186} INFO - Started process (PID=398) to work on /opt/airflow/dags/first_dag.py
[2024-12-30T08:31:15.320+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-12-30T08:31:15.321+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:31:15.321+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-12-30T08:31:15.328+0000] {logging_mixin.py:190} INFO - [2024-12-30T08:31:15.328+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 2
    from airflow
                ^
SyntaxError: invalid syntax
[2024-12-30T08:31:15.329+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-12-30T08:31:15.339+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.023 seconds
