[2024-12-30T08:56:36.345+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-30T08:56:36.359+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag_v3.third_task manual__2024-12-30T08:56:33.818056+00:00 [queued]>
[2024-12-30T08:56:36.366+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag_v3.third_task manual__2024-12-30T08:56:33.818056+00:00 [queued]>
[2024-12-30T08:56:36.367+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-12-30T08:56:36.376+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): third_task> on 2024-12-30 08:56:33.818056+00:00
[2024-12-30T08:56:36.381+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=632) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-30T08:56:36.382+0000] {standard_task_runner.py:72} INFO - Started process 633 to run task
[2024-12-30T08:56:36.382+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'first_dag_v3', 'third_task', 'manual__2024-12-30T08:56:33.818056+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/bash_operator_dag.py', '--cfg-path', '/tmp/tmpxs1bt3s_']
[2024-12-30T08:56:36.383+0000] {standard_task_runner.py:105} INFO - Job 15: Subtask third_task
[2024-12-30T08:56:36.413+0000] {task_command.py:467} INFO - Running <TaskInstance: first_dag_v3.third_task manual__2024-12-30T08:56:33.818056+00:00 [running]> on host b0ef9544b3b5
[2024-12-30T08:56:36.461+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='tanzid' AIRFLOW_CTX_DAG_ID='first_dag_v3' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-30T08:56:33.818056+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-30T08:56:33.818056+00:00'
[2024-12-30T08:56:36.462+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-30T08:56:36.475+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-30T08:56:36.477+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world, this is the third task following first task with second task']
[2024-12-30T08:56:36.484+0000] {subprocess.py:99} INFO - Output:
[2024-12-30T08:56:36.485+0000] {subprocess.py:106} INFO - hello world, this is the third task following first task with second task
[2024-12-30T08:56:36.485+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2024-12-30T08:56:36.501+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-30T08:56:36.501+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=first_dag_v3, task_id=third_task, run_id=manual__2024-12-30T08:56:33.818056+00:00, execution_date=20241230T085633, start_date=20241230T085636, end_date=20241230T085636
[2024-12-30T08:56:36.517+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-30T08:56:36.527+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-30T08:56:36.529+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
